server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lanca_articles?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: ${mysql_username:root}
    password: ${mysql_password:root}
    driver- class-name: com.mysql.jdbc.Driver # mysql数据库驱动
